- job:
    name: ui-cookiecutter-tox-checkbuild
    parent: tox
    pre-run: playbooks/checkbuild/pre.yaml
    post-run: playbooks/checkbuild/post.yaml
    vars:
      tox_envlist: checkbuild

- project:
    check:
      jobs:
        - ui-cookiecutter-tox-checkbuild
    gate:
      jobs:
        - ui-cookiecutter-tox-checkbuild
