- hosts: all
  roles:
    - role: fetch-tox-output
      tox_envlist: checkbuild
      zuul_work_dir: "{{ zuul.project.src_dir }}"

- hosts: all
  roles:
    - role: fetch-tox-output
      tox_envlist: pep8,py36-local,py36dj22-local,eslint,karma,karma-local,docs-local,releasenotes
      zuul_work_dir: "{{ zuul.project.src_dir }}/.tox/checkbuild/cafe-ui"

